# -------------------------------------------------------------------------------------------------------------------------- #
#                                              General Configuration                                                         #
# -------------------------------------------------------------------------------------------------------------------------- #
# If you are unsure of how to use this file but would like to change how the plugin shows text, visit the BukkitDev page at: #
# https://www.spigotmc.org/resources/proskillapi-create-custom-races-classes-skills-spells-with-an-easy-online-editor.91913/ #
# and look at the default configuration section                                                                              #
# -------------------------------------------------------------------------------------------------------------------------- #
Accounts:
  #
  # The main class group used for GUI displays
  main-class-group: class
  #
  # Allows one "account" per class, providing the "/class switch"
  # command to change between them. This is an alternative to
  # using "/class acc <id>" which professes as a class at the same
  # time and makes it easier to correlate an account to a class.
  # This will not work well if you have one common class
  # that turns into the rest.
  one-per-class: false
  #
  # The max number of accounts a normal user can use
  max-accounts: 3
  #
  # The max number of accounts users can have with certain permissions
  # must be in the format '<permission>:<accounts>'
  # Note that you can use 'skillapi.max_accounts.<accounts> instead'
  perm-accounts:
  - 'skillapi.account.admin:10'
#
# While targeting settings aren't necessary most of the time,
# they can help make running ally checks much faster if
# you are able to use them.
Targeting:
  #
  # Whether all monsters are enemies.
  # If you are using pets that include zombies/spiders/etc,
  # you shouldn't enable this.
  # If you want to enable it for specific worlds, list out the
  # worlds it should apply to in a list format such as:
  # monsters-enemy:
  # - world1
  # - world2
  monsters-enemy: false
  #
  # Whether all passive mobs are allies.
  # If there are custom passive mobs that you can fight,
  # you should not enable this.
  # If you want to enable it for specific worlds, list out the
  # worlds it should apply to in a list format such as:
  # passive-ally:
  # - world1
  # - world2
  passive-ally: false
  #
  # Whether all players are allies.
  # If you have any PvP, this should not be enabled.
  # If you want to enable it for specific worlds, list out the
  # worlds it should apply to in a list format such as:
  # player-ally:
  # - world1
  # - world2
  player-ally: false
  #
  # Whether for skills to affect NPCs
  affect-npcs: false
  #
  # Whether for skills to affect armor stands
  affect-armor-stands: false
#
Saving:
  #
  # Whether to auto save data periodically
  auto-save: false
  #
  # How often to auto-save in minutes
  minutes: 30
  #
  # Whether to use an SQL database to save
  sql-database: false
  #
  # Details for connecting to the database
  sql-details:
    host: localhost
    port: 54321
    database: plugins
    username: username
    password: password
    # Time to wait on loading data from the SQL database in ticks.
    # Can be used to give time for other servers to synchronize data. Note:
    # this does not apply when loading player data on server startup since
    # players wouldn't be coming from another server.
    delay: 0
#
Classes:
  #
  # Whether to use SkillAPI's health system
  modify-health: true
  #
  # The default health for players without a class
  classless-hp: 20
  #
  # Whether non-castable auto-leveled skills are shown
  show-auto-skills: false
  #
  # Whether attributes are enabled
  attributes-enabled: true
  #
  # Whether attributes can be refunded
  attributes-downgrade: false
  #
  # Price player need to pay to downgrade their attributes, set to 0 to disable (need Vault)
  attributes-downgrade-price: 0
  #
  # This casts the dynamic skill for the player when they level up,
  # allowing you to use dynamic mechanics for level up effects. If
  # there is no existing dynamic skill with the name, no effect
  # will be played. For level-specific effects, use the level condition.
  level-up-skill: 'lvlup'
#
Mana:
  #
  # Whether to use SkillAPI's mana system
  enabled: true
  #
  # How frequently mana is gained in seconds
  freq: 1
#
Skills:
  #
  # Whether players are allowed to downgrade skills
  allow-downgrade: true
  #
  # Whether messages should be shown on casting a skill
  show-messages: true
  #
  # The radius in which to show cast messages to nearby players
  message-radius: 20
  #
  # Whether to apply damage knock-back when damage is blocked
  # by defensive or offensive buffs and de-buffs
  knockback-no-damage: false
  #
  # If set to true, using /class changeclass will refund skill points back to the
  # player. If false, no refund will take place.
  refund-on-change: true
  #
  # Blocks to ignore when using the Block mechanic in dynamic skills
  # End values in an * to do all materials containing the value
  block-filter:
  - 'chest'
  - 'ender chest'
  - 'trapped chest'
  - 'redstone*'
  - 'oak sign'
  - 'spruce sign'
  - 'birch sign'
  - 'jungle sign'
  - 'acacia sign'
  - 'dark oak sign'
  - 'crimson sign'
  - 'warped sign'
  - 'spruce wall sign'
  - 'birch wall sign'
  - 'jungle wall sign'
  - 'acacia wall sign'
  - 'dark oak wall sign'
  - 'crimson wall sign'
  - 'warped wall sign'
#
Items:
  #
  # Whether to check for class, level, and attribute
  # requirements in an item's lore
  lore-requirements: false
  #
  # Whether to check for skill requirements
  # in an item's lore
  skill-requirements: false
  #
  # Whether to check for stat bonuses in an item's lore
  lore-attributes: false
  #
  # Whether to drop weapons when unable to use them
  drop-weapon: false
  #
  # The text used for class requirements in the lore
  lore-class-text: 'Class Req: '
  #
  # The text used for skill requirements in lore
  lore-skill-text: 'Requires {skill}: '
  #
  # the text used for level requirements in the lore
  lore-level-text: 'Level Req: '
  #
  # The text used for excluded classes in the lore
  lore-exclude-text: 'Excluded Class: '
  #
  # The text used for attribute requirements
  lore-attribute-text: '{attr} Req: '
  #
  # The text used for providing attributes
  attribute-text: '{attr}: '
  #
  # The slots to check for items in and apply requirements to.
  # This does not include held item, as that fluctuates and is assumed
  # Slots are based on the following:
  # 0-8 = hot bar
  # 9-35 = main inventory
  # 36 = boots
  # 37 = leggings
  # 38 = chestplate
  # 39 = helmet
  # 40 = off hand
  slots:
  - 36
  - 37
  - 38
  - 39
  - 40
#
GUI:
  #
  # Whether to lock the health bar to 10 hearts
  # This does not affect total health, only the display
  old-health-bar: true
  #
  # Should the health bar be downscaled to real health if the max is under 20?
  downscale-under: false
  #
  # Whether to force SkillAPI to override
  # health scaling of other plugins
  force-scaling: false
  #
  # This is what to display using the level bar, if anything.
  # Options are: none, mana, level
  level-bar: level
  #
  # This is what to display using the food bar, if anything.
  # Options are: none, mana, exp
  food-bar: none
  #
  # Whether to use the action bar
  use-action-bar: false
  #
  # The text to display on the action bar.
  # Available filters:
  #   {combo}       - the player's current click combo
  #   {class}       - the player's main class name
  #   {level}       - the player's main class level
  #   {exp}         - the player's main class exp
  #   {expReq}      - the player's main class required experience
  #   {expLeft}     - the player's main class experience until the next level
  #   {health}      - the player's current health
  #   {maxHealth}   - the player's max health
  #   {mana}        - the player's current mana
  #   {maxMana}     - the player's max mana
  #   {name}        - the name of the player
  #   {attr}        - the player's attribute points
  #   {sp}          - the player's main class skill points
  #   {value:<key>} - a skill value
  action-bar-text: '{combo}'
  #
  # Whether to use title messages
  title-enabled: false
  #
  # Duration for title messages in seconds
  title-duration: 3
  #
  # Fade in time for title messages in seconds
  title-fade-in: 0.5
  #
  # Fade out time for title messages in seconds
  title-fade-out: 0.5
  #
  # Messages to display using the Title bar
  # Second lines of messages will be displayed in the subtitle
  # Ones you can use include:
  #   level_up
  #   level_down
  #   exp_gained
  #   exp_lost
  #   status
  #   combo
  title-messages:
  - level_up
  - exp_lost
  #
  # Whether to add a prefix to players with their class name
  show-class-name: true
  #
  # Whether to display a player's level below their name
  show-class-level: true
  #
  # The text to show with the player's level when enabled.
  # This always appears as {level} {text}
  class-level-text: 'Level'
  #
  # Whether to append text to skill icons to show what type of item the skill is bound to
  show-binds: false
  #
  # Text to show for bound materials
  show-bind-text: 'Bound to {material}'
#
PVP:
  #
  #The minimum level the player must be to be able to PVP with other players. -1 disables this option.
  min-level: -1
  #
  #The maximum level difference two players must have to be able to PVP. -1 disables this option.
  level-range: -1
#
Casting:
  #
  # Whether the main casting option is enabled
  enabled: true

  # What casting mode to use. Available options are:
  # ITEM:
  # - The casting slot is set to a casting item
  # - Left/Right clicking on item cycles through skills
  # - Preview skill components while hovering the item
  # - No limit on skills (though makes cycling hard to find skills)
  # BARS:
  # - The casting slot is set to a casting item
  # - Left clicking on item opens hover bar
  # - Preview skill components while in hover bar the item
  # - Dropping skill indicator while in hover bar casts the skill
  # - Right clicking on item opens instant bar
  # - Selecting a slot while in instant bar immediately casts the skill
  # - Skills are assigned through the /class skill menu
  # - Limited number of skills can be put on skill bars
  # COMBAT:
  # - The casting slot becomes a toggle item
  # - Swaps between combat mode and passive mode
  # - In combat mode, works like the instant skill bar
  # - In passive mode, no skills are shown
  # - Skills are assigned through the /class skill menu
  # ACTION_BAR:
  # - Hand swapping (F by default) enters casting mode
  # - Assigned skills are displayed in the action bar
  # - Pressing the corresponding number key casts the desired skill
  # - Skills are assigned through the /class skill menu
  # TITLE:
  # - Hand swapping (F by default) enters casting mode
  # - Assigned skills are displayed as a title
  # - Pressing the corresponding number key casts the desired skill
  # - Skills are assigned through the /class skill menu
  # SUBTITLE:
  # - Hand swapping (F by default) enters casting mode
  # - Assigned skills are displayed as a subtitle
  # - Pressing the corresponding number key casts the desired skill
  # - Skills are assigned through the /class skill menu
  # CHAT:
  # - Hand swapping (F by default) enters casting mode
  # - Assigned skills are displayed in the chat
  # - Pressing the corresponding number key casts the desired skill
  # - Skills are assigned through the /class skill menu
  mode: ACTION_BAR
  #
  # Global cooldown between skill casts in seconds
  cooldown: 0
  #
  # The slot the item is kept in, must be in the range 1-9
  slot: 9
  #
  # The item to use in the cast slot.
  # When not using bars, this only shows up when no skills
  # are available for use.
  item:
    type: BOOK
    data: 0
    durability: 0
    name: '&dSkills'
    lore:
    - ''
    - '&6Left Click&2 - First skill set'
    - '&6Right Click&2 - Second skill set'
    - '&6Q&2 - Organize skills'
  #
  # The item used in the bar GUI to describe the hover bar
  hover-item:
    type: BOOKSHELF
    data: 0
    durability: 0
    name: '&6Hover Bar'
    lore:
    - ''
    - 'Skills in this row will'
    - 'be usable via left clicking'
    - 'the cast item and will let'
    - 'you see where they will hit'
    - 'before casting them.'
  #
  # The item used in the bar GUI to describe the instant bar
  instant-item:
    type: BOOKSHELF
    data: 0
    durability: 0
    name: '&6Instant Bar'
    lore:
    - ''
    - 'Skills in this row will'
    - 'be usable via right clicking'
    - 'the cast item and will be'
    - 'cast immediately when switching'
    - 'to their slot.'
  #
  # The format for skills displayed while on a text casting mode (action-bar, title, subtitle or chat)
  message-mode-format:
    skill: "&6[%number%] &a%skill%"
    separator: "&7 - "

#
Click Combos:
  #
  # Whether to use click combinations
  enabled: false
  #
  # Whether players can customize their combos
  allow-custom: false
  #
  # Whether to automatically assign combos to skills
  # without a combo manually defined. When disabled, only skills
  # configured to have a combo or have had a combo set by
  # a command will have combos.
  auto-assign: true
  #
  # Whether left clicks are allowed at all
  use-click-left: true
  #
  # Whether right clicks are allowed at all
  use-click-right: true
  #
  # Whether shift clicks are allowed at all
  use-click-shift: false
  #
  # Whether right shift clicks are allowed at all
  # This will disable "use-click-shift" if enabled
  use-click-right-shift: false
  #
  # Whether left shift clicks are allowed at all
  # This will disable "use-click-shift" if enabled
  use-click-left-shift: false
  #
  # Whether jump clicks are allowed at all
  use-click-space: false
  #
  # Whether Q clicks are allowed at all.
  # Enabling this disables dropping items via Q outside of menus.
  use-click-q: false
  #
  # Whether F clicks are allowed at all.
  # Enabling this disables swapping items between main and off hand via F.
  use-click-f: false
  #
  # How many clicks are needed to perform a combo
  combo-size: 4
  #
  # Inactivity time in seconds before clicks for a combo are reset
  click-time: 1.0
#
Skill Bar:
  #
  # Whether to use skill bars
  enabled: false
  #
  # Whether to show skill cooldowns in the skill bar
  show-cooldown: true
  #
  # The item to use as a placeholder in the skill bar
  empty-icon:
    material: PUMPKIN_SEEDS
    durability: 0
    data: 0
    text: '&7Unassigned'
  #
  # The default layout for skill bars
  # Players can customize unlocked slots
  layout:
    1:
      skill: true
      locked: false
    2:
      skill: true
      locked: false
    3:
      skill: true
      locked: false
    4:
      skill: true
      locked: false
    5:
      skill: true
      locked: false
    6:
      skill: false
      locked: false
    7:
      skill: false
      locked: false
    8:
      skill: false
      locked: false
    9:
      skill: false
      locked: false
#
Experience:
  #
  # Whether to use vanilla exp drops for class exp
  # Note: any dropped exp will not count towards class exp,
  # only enabled sources will count. By default, this is only
  # mob deaths.
  use-exp-orbs: true
  #
  # Whether to prevent gaining experience from mobs
  # spawned via a mob spawner block
  block-mob-spawner: true
  #
  # Whether to prevent gaining experience from mobs
  # spawned via a mob spawn egg
  block-mob-egg: true
  #
  # Whether to prevent gaining experience while
  # in creative mode
  block-creative: true
  #
  # Whether to display a message when gaining experience
  exp-message-enabled: true
  #
  # Whether to display a message when gaining a level
  level-message-enabled: true
  #
  # Whether to show a message when losing exp
  lose-exp-message: true
  #
  # Whether to display a message when losing a level
  lose-level-message: true
  #
  # Worlds where experience is not lost on death
  lose-exp-blacklist:
  - 'pvpWorld'
  #
  # If false use formula
  # If true use levels.yml
  use-levels: false
  #
  # The formula used for calculating required experience
  # The formula is: x*lvl*lvl + y*lvl + z
  formula:
    x: 1
    y: 8
    z: 16
  #
  # Whether to use a custom equation
  use-custom: false
  #
  # The custom formula to use with 'lvl' being the current player level
  # Note: this formula does not use x, y, or z. Use numbers directly
  # in the formula instead.
  custom-formula: '25(1.1^(lvl-1))'
  #
  # The experience yields from each mob type
  # When exp orbs are enabled, these values are ignored
  yields:
    blaze: '10'
    cavespider: '5'
    creeper: '3'
    elderguardian: '10'
    enderdragon: '400'
    enderman: '5'
    endermite: '3'
    evoker: '10'
    ghast: '5'
    giant: '20'
    guardian: '10'
    husk: '2'
    irongolem: '10'
    magmacube: '1'
    pigzombie: '5'
    player: '5'
    shulker: '5'
    silverfish: '2'
    skeleton: '3'
    slime: '1'
    spider: '3'
    stray: '5'
    vex: '3'
    vindicator: '5'
    witch: '3'
    wither: '500'
    witherskeleton: '5'
    zombie: '2'
#
# How much logging to do when loading SkillAPI
# When testing setting up skills/classes, increase this to 1-5
Logging:
  #
  # Logs for loading attributes
  attribute-load: 0
  #
  # Logs for attack/defense buffs applying
  buff: 0
  #
  # Logs for registration of skills and classes
  registration: 0
  #
  # Logs for GUI updates
  gui: 0
  #
  # Logs for mana updates
  mana: 0
#
Worlds:
  #
  # Whether to enable the world restriction
  enable: false
  #
  # Whether to use the list as an enabling list
  # If true, only worlds in the list will let players use SkillAPI
  # If false, any world not in the list will let players use SkillAPI
  use-as-enabling: true
  #
  # The worlds to include in the enable/disable list
  worlds:
  - world
#
# Customize the scoreboard here
scoreboard:
  enabled: true
  title: '&6&l%sapi_default_currentgroupname%'
  format:
  - '&2Health &c%sapi_default_scurrenthealth%'
  - '&2%sapi_default_currentmananame% &b%sapi_default_scurrentmana%'
  - '&2Level &a%sapi_default_currentlevel%'
  - '&2Exp &a%sapi_default_scurrentexp%'
  - '&2AP &a%sapi_default_attributepoints%'
  - '&2SP &a%sapi_default_skillpoints%'
