name: Dev Build

on:
  push:
    branches: [ dev ]
    paths: [ src/** ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.commits[0].author.name != 'Auto Bot'

    steps:
      - uses: actions/checkout@v3
        name: Checkout repo
        with:
          path: app
      - name: Configure git
        run: |
          git config --global user.name "Auto Bot"
          git config --global user.email "<>"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: 'Create settings.xml'
        uses: s4u/maven-settings-action@v2.8.0
        with:
          githubServer: false
          servers: '[{"id": "ossrh", "username": "Travja", "password": "${{ secrets.SONATYPE_DEPLOY_KEY }}"}]'
      - name: Publish to Maven Central
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          cd app
          mvn clean deploy -P gpg,publish -DcreateChecksum=true 2>&1 | tee log.txt
          result_code=${PIPESTATUS[0]}
          exit $result_code
      - uses: actions/checkout@v3
        name: Checkout editor branch
        with:
          ref: editor
          path: editor
      - name: Update Javadocs
        run: |
          cp -r app/gh-pages/javadocs editor/static/javadocs
          cd editor
          git add .
          git commit -m "Update javadocs"
          git push
      - name: Update version
        run: cd app && python ./.github/update_version.py true
      - name: Push to git
        run: |
          cd app
          git add .
          git commit -m "Update dev version"
          git push
      - name: Notify Discord
        run: cd app && pip install simplejson && python ./.github/notify_published.py ${{ secrets.WEBHOOK_URL }}
